### ISSUE TITLE
Add OCI Module, Setup OCI Library, and Handle Get User Profile Http Requests

### ISSUE THREAD

**Issue by Behzad-rabiei** [TogetherCrew/oci-backend#3]
### **Tasks:**
- [ ]  Add OCI Module
- [ ]  Set Up OCI Library
- [ ]   Handle get profiles http request
